--CREATE DATABASE Store;
USE Store;

CREATE TABLE Items(
Items_Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Item_Name VARCHAR(130) NOT NULL,
Item_Quantity INT NOT NULL,
Item_Price FLOAT NOT NULL,
Item_Type VARCHAR(50) NOT NULL,
Item_Weight FLOAT,
Item_Status VARCHAR(15) NOT NULL,
);

CREATE TABLE Bill(
Bill_Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Item_No INT NOT NULL,
Item_Name VARCHAR(130) NOT NULL,
Item_Quantity INT NOT NULL,
Item_Price FLOAT NOT NULL,
);

CREATE TABLE Sales(
Sales_Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Sales_amount FLOAT NOT NULL,
Sales_Day VARCHAR(50) NOT NULL,
);